image:
  repository: koush/scrypted
  tag: v0.119.1-jammy-full@sha256:5e460458151b048b08b90b1d29266433df7278f22c3b4c0c3bb5a01478eb226e
  pullPolicy: Always
liteImage:
  repository: koush/scrypted
  tag: v0.119.1-jammy-lite@sha256:4a92422820d0dfa7e822818dd168d51e418de7198e3a47db5b99029a9b3a778d
  pullPolicy: Always
nvidiaImage:
  repository: koush/scrypted
  tag: v0.119.1-jammy-nvidia@sha256:2f737e5c1e1501a452d3e82aba8b5d9383076b77d281cd3fe3e9cf0a07caaeff
  pullPolicy: Always

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 10611

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            SCRYPTED_INSECURE_PORT: "{{ .Values.service.main.ports.main.port }}"
            # SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: Bearer SET_THIS_TO_SOME_RANDOM_TEXT
            # SCRYPTED_WEBHOOK_UPDATE: http://localhost:10444/v1/update

persistence:
  server:
    enabled: true
    mountPath: /server/volume
  media:
    enabled: true
    mountPath: /media/external

portal:
  open:
    enabled: true
